WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_26024\1590714281.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_26024\1540678973.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_26024\2146481541.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_26024\458829333.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_26024\458829333.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_26024\458829333.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\458829333.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\2286716782.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\1982225004.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\2673598228.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\2673598228.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\1473676539.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\1975817723.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\1975817723.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Price = data.Close

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\3138587451.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  special_data.new_index[0] = 1262563200

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\3138587451.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  special_data.new_date[0] = datetime.datetime.fromtimestamp(special_data.new_index[0]).strftime('%Y-%m-%d %H:%M:%S')

WARNING:py.warnings:C:\Users\Skiv2\AppData\Local\Temp\ipykernel_27756\3138587451.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  special_data.new_index[i] = special_data.new_index[i - 1] + 86400

